# -*- coding: utf-8 -*-
"""imagetranscription.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZRP_M4B9IhQdOyd-Zg76_ALs2R3Jx15J
"""

!apt install -q tesseract-ocr
!pip install -q pytesseract transformers torch pillow

import os
import time
import pytesseract
from PIL import Image
import torch
from transformers import pipeline

summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

image_path = "./img.png"
while not os.path.exists(image_path):
    print("Waiting for file upload... (Upload Image in left 'Files' panel)")
    time.sleep(3)

image = Image.open(image_path).convert("RGB")
transcription = pytesseract.image_to_string(image)

summary = summarizer(transcription, max_length=100, min_length=50, do_sample=False)[0]["summary_text"]

print("\nFull Transcription:\n", transcription)
print("\nSummary:\n", summary)